language: python
sudo: false
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install: 
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
script:
  - python manage.py test
  - flake8 .
after_success:
    coveralls
